name: dart_spider
description: Simple way to scrape and extract data from websites in a structured way.
version: 0.0.8
homepage: https://github.com/sukhcha-in/dart_spider

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  http: ^0.13.4
  html: ^0.15.0

dev_dependencies:
  lints: ^2.0.0
